[phases.setup]
nixPkgs = ['python311', 'pip']
aptPkgs = []

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'python backend/app.py'

[variables]
NIXPACKS_PYTHON_VERSION = '3.11'
